[project]
name = "test-inspect-package"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sub-package",
    "inspect-ai",
]

[tool.uv.sources]
sub-package = { path = "./sub-package", editable = true }